# Generated by Django 5.1 on 2024-08-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ('id',), 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='componentes',
            options={'ordering': ('id',), 'verbose_name': 'Componente', 'verbose_name_plural': 'Componentes'},
        ),
        migrations.AlterModelOptions(
            name='escolas',
            options={'ordering': ('id',), 'verbose_name': 'Escola', 'verbose_name_plural': 'Escolas'},
        ),
        migrations.AlterModelOptions(
            name='fonte',
            options={'ordering': ('id',), 'verbose_name': 'Fonte', 'verbose_name_plural': 'Fontes'},
        ),
        migrations.AlterModelOptions(
            name='magias',
            options={'ordering': ('id',), 'verbose_name': 'Magia', 'verbose_name_plural': 'Magias'},
        ),
        migrations.AlterModelTable(
            name='classes',
            table='classes',
        ),
        migrations.AlterModelTable(
            name='componentes',
            table='componentes',
        ),
        migrations.AlterModelTable(
            name='escolas',
            table='escolas',
        ),
        migrations.AlterModelTable(
            name='fonte',
            table='fontes',
        ),
        migrations.AlterModelTable(
            name='magias',
            table='magias',
        ),
    ]
