# Generated by Django 5.1 on 2024-08-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magias', '0002_alter_classes_options_alter_componentes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magias',
            name='nivel',
            field=models.IntegerField(),
        ),
    ]
