# Generated by Django 5.1 on 2024-08-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magias', '0003_alter_magias_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magias',
            old_name='descicao',
            new_name='descricao',
        ),
    ]
