# Generated by Django 5.1 on 2024-08-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magias', '0006_alter_magias_tipo_dado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magias',
            name='tempo_conjuracao',
            field=models.CharField(max_length=50),
        ),
    ]
