# Generated by Django 5.1 on 2024-08-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magias', '0007_alter_magias_tempo_conjuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='magias',
            name='material_descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
