# Generated by Django 5.1 on 2024-08-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magias', '0008_magias_material_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolas',
            name='cor',
            field=models.CharField(blank=True, help_text='Insira uma cor em formato hexadecimal, ex: #FF5733', max_length=7, null=True),
        ),
    ]
