# Generated by Django 5.1 on 2024-08-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magias', '0009_escolas_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='magias',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='magias/', verbose_name='Imagem da Magia'),
        ),
    ]
